services:
  - type: worker
    name: skycheap-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: KIWI_API_KEY
        sync: false
      - key: ADMIN_IDS
        value: "2066158453"
      - key: CHANNEL_ID
        value: "@skycheapbot"
      - key: CHANNEL_LINK
        value: "https://t.me/skycheapbot"
      - key: BOT_USERNAME
        value: "SkyCheapBot"
    disk:
      name: skycheap-data
      mountPath: /var/data
      sizeGB: 1
