services:
  - type: worker
    name: ddflatsbot
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8655267832:AAHG9jPbmT3UmT4TeHA4xy3IuHSPjJiY4cI
      - key: DATA_DIR
        value: /var/data
    disk:
      name: flatsbot-data
      mountPath: /var/data
      sizeGB: 1
