services:
  - type: worker
    name: skycheap-bot
    env: python
    buildCommand: pip install -r FlightsBot/requirements.txt
    startCommand: cd FlightsBot && python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8611527220:AAFH5ClovMuUp7h3-rXscWPucEVQwNacYFs"
      - key: ADMIN_IDS
        value: "2066158453"
      - key: CHANNEL_ID
        value: "@DDfrets"
      - key: CHANNEL_LINK
        value: "https://t.me/DDfrets"
      - key: BOT_USERNAME
        value: "DDSkyCheapBot"
    disk:
      name: skycheap-data
      mountPath: /var/data
      sizeGB: 1
